fastlane_version '2.212.2'

skip_docs

platform :android do 
    desc "Build"
    lane :build do
      gradle(task: 'clean', project_dir: 'android/')
      gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
    end

    desc "Deploy"
    lane :deploy do
      upload_to_play_store(
        track: "internal",
        aab: "android/app/build/outputs/bundle/release/app-release.aab",
        package_name: "nz.geek.colin.scansavvy",
        json_key: ENV['GOOGLE_PLAY_JSON_KEY']
      )
    end
  end

  platform :ios do
    desc "Build"
    lane :build do
      update_code_signing_settings(
        use_automatic_signing: false,
        path: "ios/ScanSavvy.xcodeproj",
        team_id: "7AK94PMMKB",
        code_sign_identity: "Apple Distribution: Colin Campbell (7AK94PMMKB)",
      )
      update_project_provisioning(
        xcodeproj: "ios/ScanSavvy.xcodeproj",
        profile: "/Users/runner/Library/MobileDevice/Provisioning Profiles/build.mobileprovision"
      )
      cocoapods(
        podfile: "ios/Podfile"
      )
      build_app(
        scheme: "ScanSavvy",
        workspace: "ios/ScanSavvy.xcworkspace",
        export_method: "app-store",
      )
    end
  end
